### PR TITLE
Create initial version for Honister Release of Yocto

### PR DESCRIPTION
**Pull request by mc-randall**
- Changed compatibility to 'honister'
- Updated deprecated syntax
- Removed requirement for python3-typing, because typing is already included in python3 recipe

### CODE REVIEW

**Comment by phako** [comment]
wonder if we can just make the kirtsone branch also support honister, because the bulk of the changes, the syntax adaption, is already in that

**Comment by mc-randall** [comment]
> wonder if we can just make the kirtsone branch also support honister, because the bulk of the changes, the syntax adaption, is already in that

Sounds like a good idea. Just to try things out, I checked out the 'kirkstone' branch in my layer stack, replaced the outdated recipe deviceaccess_03.07.01 with the one from 'pre_honister' and copied the bbappend for boost_1.77 to 'kirkstone' as well. I also had to increase the priority of meta-chimeratk in local.conf from 6 to 7, because otherwise 'exprtk' from './meta-openembedded/meta-oe/recipes-devtools' is used and not the version of the ChimeraTK repo. @phako You would probably have check which 'exprtk' makes sense.

Now I'm stuck with the following error:

```
Could NOT find ChimeraTK-cppext: Found unsuitable version "01.04", but
|   required is at least "01.05" (found /usr)
```

**Comment by phako** [comment]
Yeah I have to look into the exprtk thing, there is already an open ticket. I try to work my way throught he Yocto stuff this week

**Comment by phako** [comment]
I have force-pushed a variant for honister that builds for me (with the exprtk issue fixed) 
I will do round of updates to the latest releases next for all branches

**Pull request closed without merging**
